package com.wisecoders.jdbc.redis

import java.sql.BatchUpdateException
import java.sql.Connection
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.SQLWarning
import java.sql.Statement

class RedisStatement(conn: RedisConnection) : RedisAbstractStatement(conn), Statement {

    private val batchOps: MutableList<String> = ArrayList()

    @Throws(SQLException::class)
    override fun addBatch(sql: String) {
        batchOps.add(sql)
    }

    @Throws(SQLException::class)
    override fun cancel() {
    }

    @Throws(SQLException::class)
    override fun clearBatch() {
        batchOps.clear()
    }

    @Throws(SQLException::class)
    override fun clearWarnings() {
    }

    @Throws(SQLException::class)
    override fun close() {
        super._isClosed = true
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        autoGeneratedKeys: Int
    ): Boolean {
        return execute(sql)
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        columnIndexes: IntArray
    ): Boolean {
        return execute(sql)
    }

    @Throws(SQLException::class)
    override fun execute(
        sql: String,
        columnNames: Array<String>
    ): Boolean {
        return execute(sql)
    }

    @Throws(SQLException::class)
    override fun executeBatch(): IntArray {
        val results = IntArray(batchOps.size)

        var ops = 0
        for (sql in this.batchOps) {
            try {
                this.execute(sql)
                results[ops] = Statement.SUCCESS_NO_INFO
            } catch (e: SQLException) {
                throw BatchUpdateException(e)
            }
            ops++
        }

        return results
    }

    @Throws(SQLException::class)
    override fun executeQuery(sql: String): ResultSet? {
        this.execute(sql)
        return this.getResultSet()
    }

    @Throws(SQLException::class)
    override fun executeUpdate(sql: String): Int {
        try {
            val resultSet = RedisCommandProcessor.runCommand(super._connection, sql)

            return if ( resultSet.next()) {
                resultSet.getInt(0)
            } else {
                0
            }
        } catch (e: RedisParseException) {
            throw SQLException(e)
        } catch (e: RedisResultException) {
            throw SQLException(e)
        }
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        autoGeneratedKeys: Int
    ): Int {
        return this.executeUpdate(sql)
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        columnIndexes: IntArray
    ): Int {
        return this.executeUpdate(sql)
    }

    @Throws(SQLException::class)
    override fun executeUpdate(
        sql: String,
        columnNames: Array<String>
    ): Int {
        return this.executeUpdate(sql)
    }

    @Throws(SQLException::class)
    override fun getConnection(): Connection {
        return this._connection
    }

    @Throws(SQLException::class)
    override fun getFetchDirection(): Int {
        return 0
    }

    @Throws(SQLException::class)
    override fun getFetchSize(): Int {
        return 0
    }

    @Throws(SQLException::class)
    override fun getGeneratedKeys(): ResultSet? {
        return null
    }

    @Throws(SQLException::class)
    override fun getMaxFieldSize(): Int {
        return 0
    }

    @Throws(SQLException::class)
    override fun getMaxRows(): Int {
        return 0
    }

    @Throws(SQLException::class)
    override fun getMoreResults(): Boolean {
        return false
    }

    @Throws(SQLException::class)
    override fun getMoreResults(current: Int): Boolean {
        return false
    }

    @Throws(SQLException::class)
    override fun getQueryTimeout(): Int {
        return 0
    }

    @Throws(SQLException::class)
    override fun getResultSet(): ResultSet {
        return this._resultSet
    }

    @Throws(SQLException::class)
    override fun getResultSetConcurrency(): Int {
        return ResultSet.CONCUR_READ_ONLY
    }

    @Throws(SQLException::class)
    override fun getResultSetHoldability(): Int {
        return ResultSet.CLOSE_CURSORS_AT_COMMIT
    }

    @Throws(SQLException::class)
    override fun getResultSetType(): Int {
        return ResultSet.TYPE_FORWARD_ONLY
    }

    @Throws(SQLException::class)
    override fun getUpdateCount(): Int {
        return -1
    }

    @Throws(SQLException::class)
    override fun getWarnings(): SQLWarning? {
        return null
    }

    @Throws(SQLException::class)
    override fun isClosed(): Boolean {
        return this.isClosed
    }

    @Throws(SQLException::class)
    override fun isPoolable(): Boolean {
        return false
    }

    @Throws(SQLException::class)
    override fun setCursorName(name: String) {
    }

    @Throws(SQLException::class)
    override fun setEscapeProcessing(enable: Boolean) {
    }

    @Throws(SQLException::class)
    override fun setFetchDirection(direction: Int) {
    }

    @Throws(SQLException::class)
    override fun setFetchSize(rows: Int) {
    }

    @Throws(SQLException::class)
    override fun setMaxFieldSize(max: Int) {
    }

    @Throws(SQLException::class)
    override fun setMaxRows(max: Int) {
    }

    @Throws(SQLException::class)
    override fun setPoolable(arg0: Boolean) {
    }

    @Throws(SQLException::class)
    override fun setQueryTimeout(seconds: Int) {
    }

    @Throws(SQLException::class)
    override fun isWrapperFor(iface: Class<*>?): Boolean {
        return false
    }

    @Throws(SQLException::class)
    override fun <T> unwrap(iface: Class<T>): T? {
        return null
    }

    @Throws(SQLException::class)
    override fun closeOnCompletion() {
    }

    @Throws(SQLException::class)
    override fun isCloseOnCompletion(): Boolean {
        return false
    }
}
